CREATE TABLE IF NOT EXISTS `specialties` (
  `id` INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL
)ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `professional` (
  `id` INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `crm` VARCHAR(20) NULL,
  `specialties_id` INT UNSIGNED NOT NULL,
    FOREIGN KEY (`specialties_id`)
    REFERENCES `specialties` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `schedule` (
  `id` INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `consultation` DATETIME NULL,
  `professional_id` INT UNSIGNED NULL,
    FOREIGN KEY (`professional_id`)
    REFERENCES `professional` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
