-- MySQL Script generated by MySQL Workbench
-- sex 04 fev 2022 19:57:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema feegow-chalenge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `specialties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `specialties` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `professional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `professional` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `crm` VARCHAR(20) NULL,
  `specialties_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_professional_specialties1_idx` (`specialties_id` ASC) VISIBLE,
  UNIQUE INDEX `crm_UNIQUE` (`crm` ASC) VISIBLE,
  CONSTRAINT `fk_professional_specialties1`
    FOREIGN KEY (`specialties_id`)
    REFERENCES `specialties` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `consultation` DATETIME NULL,
  `professional_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schedule_professional_idx` (`professional_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_professional`
    FOREIGN KEY (`professional_id`)
    REFERENCES `professional` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
